### ISSUE TITLE
Feature Request: Pattern functions

### ISSUE THREAD

**Issue by wdkrnls** [coolbutuseless/flexo#1]
Not everything can be easily or concisely or reusably expressed by regexes. Do you think this framework could be readily extended to additionally support arbitrary functions returning logical TRUE given a string of characters which matches? I suppose to do that you would want to supply flexibility towards covering gready vs maximal matching. I remember this functionality coming in quite handy when parsing some milti-line file formats with TXR. I would love to see such a capability within an R tool.

**Comment by coolbutuseless** [comment]
Could you give an example of the type of text your trying to parse, and the arbitrary function you might need?

flexo is very regex focussed in order to break text into tokens with minimal effort.  I'm not yet sure how arbitrary functions would fit in the mix, but I'd need to see some example first.

**Comment by wdkrnls** [comment]
The only thing that springs to mind to me right now is detecting chemical formulas or other things which are somewhat recursively defined like lisp data notation or arithmetic.

**Comment by coolbutuseless** [comment]
No action to take. Closing.
